// project details
export const PROJECT_DETAILS_STARTED = "PROJECT_DETAILS_STARTED";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

// fetch projects
export const PROJECT_FETCH_STARTED = "PROJECT_FETCH_STARTED";
export const PROJECT_FETCH_SUCCESS = "PROJECT_FETCH_SUCCESS";
export const PROJECT_FETCH_FAIL = "PROJECT_FETCH_FAIL";
