// auth Action Types

// skill details
export const SKILL_DETAILS_STARTED = "SKILL_DETAILS_STARTED";
export const SKILL_DETAILS_SUCCESS = "SKILL_DETAILS_SUCCESS";
export const SKILL_DETAILS_FAIL = "SKILL_DETAILS_FAIL";

// Fetch
export const FETCH_SKILLS_STARTED = "FETCH_SKILLS_STARTED";
export const FETCH_SKILLS_SUCCESS = "FETCH_SKILLS_SUCCESS";
export const FETCH_SKILLS_FAIL = "FETCH_SKILLS_FAIL";